### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by jeroentbt** [cyli/logstash-output-slack#13]
It seems the systems proxy settings are not taken in to account. (at least not in the way I run logstash in a container).
Might it be a good idea to allow users to configure a proxy?

Either by doing `RestClient.proxy = ENV['http_proxy']` or 

> New in 2.0: Specify a per-request proxy by passing the `:proxy` option to `RestClient::Request`. This will override any proxies set by environment variable or by the global `RestClient.proxy` value.

**Comment by cyli** [comment]
Hi @jeroentbt!  So sorry for not responding in forever.  I haven't figured out how to test this, since it doesn't seem to pass the parameters onto the request.  

https://github.com/cyli/logstash-output-slack/pull/23

Since rest-client 2.0.0 is still in rc3, I went with the environment variable.

**Comment by jizhoubo** [comment]
to force using a proxy, i had to modify your .rb file to hard code my proxy...

`begin
    RestClient.proxy = "http://x.x.x.x:yyyy"
    RestClient.post(
        @url,
        "payload=#{CGI.escape(JSON.dump(payload_json))}",
        :accept => "application/json",
        :'User-Agent' => "logstash-output-slack",
        :content_type => @content_type) { |response, request, result, &block|
          if response.code != 200
            @logger.warn("Got a #{response.code} response: #{response}")
          end
    }
`

**Comment by cyli** [comment]
@jizhoubo - thanks for letting me know!  Did the environment variable in that branch not work?

**Comment by jeroentbt** [comment]
Thank you @cyli.
I've moved project and no longer use this, but my ex-colleagues are notified and will surely appreciate.
