### ISSUE TITLE
Variable expansion inside "username"

### ISSUE THREAD

**Issue by corradio** [cyli/logstash-output-slack#5]
I have the following configuration:

```
                slack {
                    url => "https://hooks.slack.com/services/xxx"
                    username => "%{appname}"
                    format => "[%{appname}] %{message}"
                }
```

It seems that variable expansion does not work for username (which keeps showing `%{appname}`, whereas it works for the message itself (which expands `%{appname}` into the value of the `appname` variable).

**Comment by cyli** [comment]
Ah, right, thanks!  I just [use the username string](https://github.com/cyli/logstash-output-slack/blob/master/lib/logstash/outputs/slack.rb#L49).  I think this should be an easy fix, although I may not be able to get to it until the end of the week, if that's ok?

**Comment by corradio** [comment]
Sure - let me know!

## 

Olivier Corradi

olivier.corradi@snips.net

Skype: oliviercorradi

Twitter: @corradio

LinkedIn: linkedin.com/in/oliviercorradi

VSRE compliant - vsre.info

**Comment by cyli** [comment]
@corradio Would you mind double-checking #6?  If it looks good, I'll merge.  Thanks!

**Comment by corradio** [comment]
Double checked and it looks good. Did not test it though!

## 

Olivier Corradi

olivier.corradi@snips.net

Skype: oliviercorradi

Twitter: @corradio

LinkedIn: linkedin.com/in/oliviercorradi

VSRE compliant - vsre.info

**Comment by cyli** [comment]
Ok, tested this against an instance of slack, and it seemed to work.  @corradio Do you need a new gem version released, or is master sufficient?

**Comment by corradio** [comment]
Master is sufficient if you can point me to the preferred installation procedure.

**Comment by corradio** [comment]
Actually @cyli can you make a new release? This will be much easier for new users.

**Comment by cyli** [comment]
@corradio Pushed version 0.1.1, and also updated the README for instructions on how to install from source too.  Sorry for the delay, and thank you for the review!

**Comment by corradio** [comment]
thx! When will it be pushed to the logstash plugin repository?

**Comment by cyli** [comment]
@corradio Do you mean https://github.com/logstash-plugins/logstash-output-slack/pull/1?

**Comment by corradio** [comment]
Works now :)

On Thursday, September 17, 2015, Ying Li notifications@github.com wrote:

> @corradio https://github.com/corradio Do you mean
> logstash-plugins/logstash-output-slack#1
> https://github.com/logstash-plugins/logstash-output-slack/pull/1?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cyli/logstash-output-slack/issues/5#issuecomment-140931025
> .

## 

## 

Olivier Corradi

olivier.corradi@snips.net

Skype: oliviercorradi

Twitter: @corradio

LinkedIn: linkedin.com/in/oliviercorradi

VSRE compliant - vsre.info
